code_essay/urls.py
from code_essay.views import (
    ArticleListView,
    ArticleView,
    CategoryArticleListView,
    CreateArticleView,
    IndexView,
    OfficialArticleListView,
    UserArticleListView,
)
from code_essay.converters import OrderAndPageConverter
from django.urls import register_converter, path


app_name = 'code_essay'

urlpatterns = [
    path('', IndexView.as_view(), name='index'), # トップページ
    path('article_list/', ArticleListView.as_view(), name='article_list'), # 記事一覧ページ
    path('user/<uuid:user_id>/', UserArticleListView.as_view(), name='user'), # ユーザー記事一覧ページ
    path('category/<slug:category_slug>/', CategoryArticleListView.as_view(), name='category'), # カテゴリページ
    path('official/', OfficialArticleListView.as_view(), name='official'), # 公式記事一覧ページ
    path('new/', CreateArticleView.as_view(), name='new'), # 新規記事作成ページ
    path('article/<uuid:article_id>/', ArticleView.as_view(), name='article'), # 記事ページ
    path('<slug:article_slug>/', ArticleView.as_view(), name='article_slug'), # 記事ページ（slug）
]

project/urls.py
"""
URLルーティングを行うファイル. 各アプリケーションのurl.pyに接続する.
"""

from django.contrib import admin
from django.urls import path, include

# TODO: Media
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sign.urls')), # sign関連
    path('', include('code_essay.urls')), # メイン
]

# TODO: Media
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sign/urls.py
from django.urls import path
from sign.views import *

app_name = 'sign'

urlpatterns = [

    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),

    path('sign_up/', SignUp.as_view(), name='sign_up'),
    path('sign_up/done', SignUpDone.as_view(), name='sign_up_done'),
    path('sign_up/complete/<str:token>/', SignUpComplete.as_view(), name='sign_up_complete'),

    path('user_update/<uuid:pk>/', UserUpdate.as_view(), name='user_update'),

    path('email_change/', EmailChange.as_view(), name='email_change'),
    path('email_change/done/', EmailChangeDone.as_view(), name='email_change_done'),
    path('email_change/complete/<str:token>/', EmailChangeComplete.as_view(), name='email_change_complete'),

    path('password_change/', PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDone.as_view(), name='password_change_done'),

    path('password_reset/', PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<str:token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', PasswordResetComplete.as_view(), name='password_reset_complete'),

]

code_essay/models.py
import uuid
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from sign.models import User


class Article(models.Model):

    """
    Article（記事）モデル.
    """

    id = models.UUIDField(_('article uuid key'), primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.SlugField(_('article slug'), max_length=255, unique=True, blank=True,)
    is_official = models.BooleanField(_('flag for official articles'), default=False,)
    category = models.ForeignKey('Category', on_delete=models.CASCADE,)
    author = models.ForeignKey(User, on_delete=models.CASCADE,)
    title = models.CharField(_('article title'), max_length=255,)
    contents = models.TextField(_('article contents'), blank=True,)
    is_open = models.BooleanField(_('flag for published articles'), default=True,)
    create_date = models.DateField(_('create date'), default=timezone.now,)
    update_date = models.DateField(_('update date'), auto_now=True,)
    views = models.IntegerField(_('number of views'), default=0,)
    likes = models.IntegerField(_('number of likes'), default=0,)
    del_flg = models.BooleanField(_('flag for deleted articles'), default=False,)

    class Meta:
        verbose_name = _('article')
        verbose_name_plural = _('articles')


class Category(models.Model):

    """
    Category（カテゴリ）モデル.
    """

    slug = models.SlugField(_('category slug'), max_length=255, unique=True, blank=True,)
    name = models.CharField(_('category name'), max_length=255,)
    create_date = models.DateField(_('create date'), default=timezone.now,)
    update_date = models.DateField(_('update date'), auto_now=True,)
    del_flg = models.BooleanField(_('flag for deleted categories'), default=False,)

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class Comment(models.Model):

    """
    Comment（コメント）モデル.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    contents = models.TextField(_('comment contents'), )
    create_date = models.DateField(_('create date'), default=timezone.now,)
    update_date = models.DateField(_('update date'), auto_now=True,)
    goods = models.IntegerField(_('number of user who evaluate this comment good'), default=0,)
    bads = models.IntegerField(_('number of user who evaluate this comment bad'), default=0,)
    del_flg = models.BooleanField(_('flag for deleted comments'), default=False,)

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')


class Favorite(models.Model):

    """
    Favorite（お気に入り）モデル. お気に入りをしたユーザーと, そのお気に入りをした記事を記録する.
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    articles = models.ManyToManyField('Article', blank=True,)

    class Meta:
        verbose_name = _('favorite')
        verbose_name_plural = _('favorites')

code_essay/forms.py
from django import forms
from code_essay.models import Article


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('contents', 'category', 'title', 'is_open')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if key == 'contents':
                class_name = ''
                id_name = 'js-article__textarea'
            elif key == 'category':
                class_name = ''
                id_name = ''
            elif key == 'title':
                class_name = ''
                id_name = ''
            elif key == 'is_open':
                class_name = ''
                id_name = ''
            field.widget.attrs.update({
                'class': class_name,
                'id': id_name,
            })

code_essay/views.py
from code_essay.forms import ArticleForm
from code_essay.models import Article, Comment, Category
from django.http import HttpResponseBadRequest
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView
from math import ceil
from re import sub
from sign.models import User


class IndexView(ListView):

    template_name = 'code_essay/index.html'
    model = Category
    paginate_by = 10
    queryset = Article.objects.filter(del_flg=False,)
    meta = {
        'robots': 'index, follow',
        'title': 'Topics',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'meta': self.meta,
            'category_list': Category.objects.filter(del_flg=False,),
        })
        return context


class CreateArticleView(CreateView):
    template_name = 'code_essay/article.html'
    form_class = ArticleForm
    model = Article

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, '新しいノートを作成しました')
        self.success_url = reverse_lazy('code_essay:article', form.instance.pk)
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'category_list': Category.objects.filter(del_flg=False,),
        })
        return context


class ArticleView(TemplateView):

    template_name = 'code_essay/article.html'
    meta = {
        'robots': 'index, follow',
        'title': '',
    }

    def get(self, request, **kwargs):
        article_id = kwargs.get('article_id')
        article_slug = kwargs.get('article_slug')
        if article_id:
            try:
                self.article = Article.objects.get(pk=article_id)
            except Article.DoesNotExist:
                return HttpResponseBadRequest()
        elif article_slug:
            try:
                self.article = Article.objects.get(slug=article_slug)
            except Article.DoesNotExist:
                return HttpResponseBadRequest()
        return super().get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.article.views += 1
        self.article.save()
        self.meta['title'] = self.article.title
        context.update({
            'article': self.article,
            'category_list': Category.objects.filter(del_flg=False,),
            'comment_list': Comment.objects.filter(article=self.article),
            'meta': self.meta,
        })
        return context

    def post(self, request, **kwargs):
        # コメントの受け取り処理
        # 記事の修正受け取り処理
        # お気に入り受け取り処理n etc...
        pass


class ArticleListView(ListView):

    template_name = 'code_essay/article_list.html'
    model = Article
    paginate_by = 10
    queryset = Article.objects.filter(del_flg=False, is_official=False, is_open=True,)
    meta = {
        'robots': 'noindex, follow',
        'title': 'ノート一覧',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'meta': self.meta,
            'category_list': Category.objects.filter(del_flg=False,),
        })
        return context


class UserArticleListView(ListView):

    template_name = 'code_essay/article_list.html'
    model = Article
    paginate_by = 10
    queryset = Article.objects.filter(del_flg=False, is_official=False, is_open=True,)
    meta = {'robots': 'noindex, follow',}

    def get(self, request, **kwargs):
        user_id = kwargs.get('user_id')
        try:
            self.user = User.objects.get(pk=user_id, is_active=True)
        except User.DoesNotExist:
            return HttpResponseBadRequest()
        return super().get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.meta['title'] = '{} のノート一覧'.format(self.user.display_name)
        self.queryset = self.queryset.filter(author=self.user,)
        context.update({
            'meta': self.meta,
            'category_list': Category.objects.filter(del_flg=False,),
            'display_user': self.user,
        })
        return context


class CategoryArticleListView(ListView):

    template_name = 'code_essay/article_list.html'
    model = Article
    paginate_by = 10
    queryset = Article.objects.filter(del_flg=False, is_official=False, is_open=True,)
    meta = {'robots': 'noindex, follow',}

    def get(self, request, **kwargs):
        category_slug = kwargs.get('category_slug')
        try:
            self.category = Category.objects.get(del_flg=False, slug=category_slug)
        except Category.DoesNotExist:
            return HttpResponseBadRequest()
        return super().get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.meta['title'] = '{} のノート一覧'.format(self.category.name)
        self.queryset = self.queryset.filter(category=self.category,)
        context.update({
            'meta': self.meta,
            'category_list': Category.objects.filter(del_flg=False,),
        })
        return context


class OfficialArticleListView(ListView):

    template_name = 'code_essay/article_list.html'
    model = Article
    paginate_by = 10
    queryset = Article.objects.filter(del_flg=False, is_official=True, is_open=True,)
    meta = {
        'robots': 'noindex, follow',
        'title': 'Code Essay 運営チーム',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'meta': self.meta,
            'category_list': Category.objects.filter(del_flg=False,),
        })
        return context

code_essay/templates/base/base.html
{% load static %}

<!DOCTYPE html>

<html lang = "ja">

  {% include './head.html' %}

  <body>

    {% include './header.html' %}
    {% include './search.html' %}
    {% block contents %}
    {% endblock %}
    {% include './footer.html' %}

  </body>

</html>

code_essay/templates/base/footer.html
{% load static %}

<footer class="footer">

  <ul class="footer__menu">
    <li class="footer__menu-item"><a href="{% url 'code_essay:article_slug' 'terms' %}">Terms</a>
    <li class="footer__menu-item"><a href="{% url 'code_essay:article_slug' 'privacy' %}">Privacy</a>
    <li class="footer__menu-item"><a href="{% url 'code_essay:article_slug' 'contact' %}">Contact</a>
    <li class="footer__menu-item"><a href="{% url 'code_essay:official' %}">Blog</a>
    <li class="footer__menu-item"><a href="{% url 'code_essay:article_slug' 'about' %}">About</a>
    <li class="footer__menu-item">© 2019 tsux
  </ul>

</footer>

code_essay/templates/base/head.html
{% load static %}

<head>

  <meta charset = "utf-8">
  <meta http-equiv = "X-UA-Compatible" content = "IE = edge">
  <meta name = "viewport" content = "width = device-width, initial-scale = 1">

  <meta name = "robots" content = "{{ meta.robots }}">

  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <!-- <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho|Sawarabi+Gothic" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Merriweather|Ubuntu" rel="stylesheet"> -->

  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/marked.js' %}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_CHTML"></script>
  <script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ["\\(","\\)"]], displayMath: [['$$','$$'], ["\\[","\\]"]]}});</script>
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/editor.js' %}"></script>

  <title>{{ meta.title }} - Code Essay</title>

</head>

code_essay/templates/base/header.html
{% load static %}

<header class="header">

  <i class="fas fa-bars header__menu-icon header__item" id="js-header__menu-icon"></i>
  <a class="header__title header__item" href="{% url 'code_essay:index' %}">Code Essay</a>

  <div class="user-menu">
    {% if request.user.is_authenticated %}
    <a class="user-menu__item" href="{% url 'code_essay:new' %}"><i class="fas fa-plus"></i> Create</a>
    <i class="fas fa-user fa-border user-menu__item user-menu__user-icon" id="js-user__menu--others"></i>
    <ul class="user__others-menu" id="js-user__others-menu">
      <li class="user__others-menu-item-title"><span>Signed as {{ request.user.display_name }}.</span>
      <li class="user__others-menu-item"><a href="{% url 'code_essay:user' request.user.pk %}">My Page</a>
      <li class="user__others-menu-item"><a href="{% url 'sign:user_update' request.user.pk %}">Profile Settings</a>
      <li class="user__others-menu-item"><a href="{% url 'sign:password_change' %}">Password Change</a>
      <li class="user__others-menu-item"><a href="{% url 'sign:email_change' %}">Email Change</a>
      <li class="user__others-menu-item"><a href="{% url 'sign:logout' %}">Logout</a>
    </ul>
    {% else %}
    <a class="user-menu__item" href="{% url 'sign:login' %}">Sign in</a>
    <a class="user-menu__item" href="{% url 'sign:sign_up' %}">Sign up</a>
    {% endif %}
  </div>

</header>

code_essay/templates/base/search.html
{% load static %}

<nav class="search" id="js-search">

  <form class="search__form" action="{% url 'code_essay:article_list' %}" post="get">
    <div>
      <input class="search__keyword-input" id="" name="keywords" type="text" placeholder="Search">
      <div>
        <select class="search__order-box" name="order" id="js-search__order">
          <option class="search__order-item" value="-views">Recommend</option>
          <option class="search__order-item" value="-create_date">Newest</option>
          <option class="search__order-item" value="create_date">Oldest</option>
        </select>
        <select class="search__category-box" name="category" id="js-search__category">
          <option class="search__category-item" value="all">all</option>
          <option class="search__category-item" value="user">your articles</option>
          <option class="search__category-item" value="official">official</option>
          <optgroup label="Categories">
            {% for category in category_list %}
            <option class="search__category-item" value="{{ category.slug }}">{{ category.name }}</option>
            {% endfor %}
          </optgroup>
        </select>
      </div>
    </div>
    <button class="search__submit" id="" type="submit">
      <i class="fas fa-search"></i>
    </button>
  </form>

  <ul class="search__category-list">
    <li class="search__category-item">
      <a href="{% url 'code_essay:article_list' %}"><i class="fab fa-diaspora fa-fw"></i> All Articles</a>
    </li>
    {% if request.user.is_authenticated %}
    <li class="search__category-item">
      <a href="{% url 'code_essay:user' request.user.pk %}"><i class="fab fa-diaspora fa-fw"></i> Your Articles</a>
    </li>
    {% endif %}
    <li class="search__category-item">
      <a href="{% url 'code_essay:official' %}"><i class="fab fa-diaspora fa-fw"></i> Official</a>
    </li>
    <li>
      <div class="search__category-item"><i class="fas fa-chevron-right fa-fw"></i> Categories</div>
      <ul class="search__category-list">
        {% for category in category_list %}
        <li class="search__category-item">
          <a href="{% url 'code_essay:category' category.slug %}"><i class="fab fa-diaspora fa-fw"></i> {{ category.name }}</a>
        </li>
        {% endfor %}
      </ul>
    </li>
  </ul>

</nav>